import { Metadata } from "next";
import { auth } from "@/auth";
export const metadata: Metadata = {
  title: "Twój koszyk | RIGBA",
  description: "Generated by create next app",
};

export default async function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
