import { Metadata } from "next";
import { auth } from "@/auth";
import CheckoutHeader from "@/components/Interface/Shared/CheckoutHeader/CheckoutHeader";

export const metadata: Metadata = {
  title: "Twój koszyk | RIGBA",
  description: "Generated by create next app",
};

export default async function Checkout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return (
    <html lang="en">
      <body>
        <CheckoutHeader />
        {children}
      </body>
    </html>
  );
}
