import { Metadata } from "next";
import HeaderContainer from "@/components/Interface/Header/HeaderContainer";
import NavbarContainer from "@/components/Interface/Navbar/NavbarContainer";

export const metadata: Metadata = {
  title: "Buy, browse, learn everything about games | RIGBA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <HeaderContainer />
        <NavbarContainer />
        {children}
      </body>
    </html>
  );
}
