import { Metadata } from "next";
import { workbench } from "../utils/fonts";
import "./globals.css";
import Header from "@/components/Interface/Shared/Header/Header";
import Navbar from "@/components/Interface/Shared/Navbar/Navbar";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata: Metadata = {
  title: "Buy, browse, learn everything about games | RIGBA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Header />
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
