export default function Navbar() {
  return (
    <>
      <nav className="bg-[#244673]">
        <ul className="text-[white] flex items-center mx-auto max-w-[1240px] w-full py-3 px-3 gap-10 text-[18px]">
          <li>
            <a
              href="
            "
            >
              Sklep
            </a>
          </li>
          <li>
            <a
              href="
            "
            >
              Gry
            </a>
          </li>
          <li>
            <a
              href="
            "
            >
              Karty do gier
            </a>
          </li>
          <li>
            <a
              href="
            "
            >
              eKarty
            </a>
          </li>
          <li>
            <a
              href="
            "
            >
              Xbox
            </a>
          </li>
          <li>
            <a
              href="
            "
            >
              PSN
            </a>
          </li>
          <li>
            <a
              href="
            "
            >
              Nintendo
            </a>
          </li>
        </ul>
      </nav>
    </>
  );
}
